### ISSUE TITLE
API rate limit exceeded for *

### ISSUE THREAD

**Issue by blyxyas** [Altair-Bueno/altair-bueno.github.io#33]
When visiting the page for the first time, it seems that the API rate limit is set to 1 or the client makes unvoluntary requests, as it triggers a 403 error:

**Heads up!** Error: API rate limit exceeded for [IP] (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

I'm pretty sure it has to do with Astro. Maybe some misconfiguration

**Comment by Altair-Bueno** [comment]
Looks good to me on incognito. I think you just hit GitHub's API limit. Have you tried using a different public IP? 

A shared public IP with more people is often the cause. ISP's NAT, VPN's (Apple's private browsing is turn on by default if you are subscribed to iCloud+), ppl browsing GitHub services without logging in, just to name a few. 

![image](https://github.com/Altair-Bueno/altair-bueno.github.io/assets/67512202/2b260eda-c6ff-4517-b7c2-8b634bff5eab)

**Comment by blyxyas** [comment]
I haven't tried using another IP, but I'd guess that the API limit is also for the main GitHub website and it works fine. I'll test some more when I get home.

Edit: Tried it with another IP, it works just fine. I'll close the issue here and investigate GitHub some more, maybe try to see another site, but maybe it was just Cloudflare being paranoid.

**Comment by Altair-Bueno** [comment]
Glad to know it resolved on its own! Thanks for stopping by😊
